version: '3.8'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  postgres:
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgloader:
    image: dimitri/pgloader:latest
    depends_on:
      - mysql
      - postgres
    volumes:
      - ./migration:/migration
    entrypoint: ['/bin/bash', '-c']
    command: ['tail -f /dev/null']

volumes:
  mysql_data:
  postgres_data:
